using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Unity.VisualScripting;
using UnityEngine;

public class GenerateNovelPipeline : GPT_Pipeline
{
    public const string TITLE = "title";
    public const string DESCRIPTION = "description";
    public const string IMAGE = "image";
    public const string NAME_OF_MAIN_CHARACTER = "nameOfMainCharacter";
    public const string ROLE_OF_TALKING_PARTNER = "roleOfTalkingPartner";
    public const string NAME_OF_TALKING_PARTNER = "nameOfTalkingPartner";
    public const string CONTEXT = "context";
    public const string BACKGROUND_SPRITE = "backgroundSprite";
    public const string LOCATION = "location";
    public const string BIASES = "biases";
    public const string EXPRESSION_TYPE_WHILE_JOINING = "expressionTypeWhileJoining";
    public const string FIRST_JSON_SCRIPT = "firstJsonScript";
    public const string SECOND_JSON_SCRIPT = "secondJsonScript";
    public const string THIRD_JSON_SCRIPT = "thirdJsonScript";
    public const string SPEAKER_01 = "speaker01";
    public const string MESSAGE_01 = "message01";
    public const string EXPRESSION_TYPE_01 = "expressionType01";
    public const string SPEAKER_02 = "speaker02";
    public const string MESSAGE_02 = "message02";
    public const string EXPRESSION_TYPE_02 = "expressionType02";
    public const string SPEAKER_03 = "speaker03";
    public const string MESSAGE_03 = "message03";
    public const string EXPRESSION_TYPE_03 = "expressionType03";
    public const string MESSAGE_04_OPTION_01 = "message04_Option01";
    public const string MESSAGE_04_OPTION_02 = "message04_Option02";
    public const string MESSAGE_04_OPTION_03 = "message04_Option03";
    public const string MESSAGE_04_OPTION_04 = "message04_Option04";
    public const string SPEAKER_05 = "speaker05";
    public const string MESSAGE_05 = "message05";
    public const string EXPRESSION_TYPE_05 = "expressionType05";
    public const string MESSAGE_06_OPTION_01 = "message06_Option01";
    public const string MESSAGE_06_OPTION_02 = "message06_Option02";
    public const string MESSAGE_06_OPTION_03 = "message06_Option03";
    public const string MESSAGE_06_OPTION_04 = "message06_Option04";
    public const string SPEAKER_07 = "speaker07";
    public const string MESSAGE_07 = "message07";
    public const string EXPRESSION_TYPE_07 = "expressionType07";
    public const string SPEAKER_08 = "speaker08";
    public const string MESSAGE_08 = "message08";
    public const string EXPRESSION_TYPE_08 = "expressionType08";
    public const string SPEAKER_09 = "speaker09";
    public const string MESSAGE_09 = "message09";
    public const string EXPRESSION_TYPE_09 = "expressionType09";
    public const string MESSAGE_10_OPTION_01 = "message10_Option01";
    public const string MESSAGE_10_OPTION_02 = "message10_Option02";
    public const string MESSAGE_10_OPTION_03 = "message10_Option03";
    public const string MESSAGE_10_OPTION_04 = "message10_Option04";
    public const string SPEAKER_11 = "speaker11";
    public const string MESSAGE_11 = "message11";
    public const string EXPRESSION_TYPE_11 = "expressionType11";
    public const string SPEAKER_12 = "speaker12";
    public const string MESSAGE_12 = "message12";
    public const string EXPRESSION_TYPE_12 = "expressionType12";
    public const string SPEAKER_13 = "speaker13";
    public const string MESSAGE_13 = "message13";
    public const string EXPRESSION_TYPE_13 = "expressionType13";
    public const string SPEAKER_14 = "speaker14";
    public const string MESSAGE_14 = "message14";
    public const string EXPRESSION_TYPE_14 = "expressionType14";
    public const string SPEAKER_15 = "speaker15";
    public const string MESSAGE_15 = "message15";
    public const string EXPRESSION_TYPE_15 = "expressionType15";
    public const string SPEAKER_16 = "speaker16";
    public const string MESSAGE_16 = "message16";
    public const string EXPRESSION_TYPE_16 = "expressionType16";
    public const string SPEAKER_17 = "speaker17";
    public const string MESSAGE_17 = "message17";
    public const string EXPRESSION_TYPE_17 = "expressionType17";
    public const string SPEAKER_18 = "speaker18";
    public const string MESSAGE_18 = "message18";
    public const string EXPRESSION_TYPE_18 = "expressionType18";
    public const string SPEAKER_19 = "speaker19";
    public const string MESSAGE_19 = "message19";
    public const string EXPRESSION_TYPE_19 = "expressionType19";
    public const string SPEAKER_20 = "speaker20";
    public const string MESSAGE_20 = "message20";
    public const string EXPRESSION_TYPE_20 = "expressionType20";
    public const string MESSAGE_21_OPTION_01 = "message21_Option01";
    public const string MESSAGE_21_OPTION_02 = "message21_Option02";
    public const string MESSAGE_21_OPTION_03 = "message21_Option03";
    public const string MESSAGE_21_OPTION_04 = "message21_Option04";
    public const string SPEAKER_22 = "speaker22";
    public const string MESSAGE_22 = "message22";
    public const string EXPRESSION_TYPE_22 = "expressionType22";
    public const string SPEAKER_23 = "speaker23";
    public const string MESSAGE_23 = "message23";
    public const string EXPRESSION_TYPE_23 = "expressionType23";
    public const string SPEAKER_24 = "speaker24";
    public const string MESSAGE_24 = "message24";
    public const string EXPRESSION_TYPE_24 = "expressionType24";
    public const string MESSAGE_25_OPTION_01 = "message25_Option01";
    public const string MESSAGE_25_OPTION_02 = "message25_Option02";
    public const string MESSAGE_25_OPTION_03 = "message25_Option03";
    public const string MESSAGE_25_OPTION_04 = "message25_Option04";
    public const string SPEAKER_26 = "speaker26";
    public const string MESSAGE_26 = "message26";
    public const string EXPRESSION_TYPE_26 = "expressionType26";
    public const string SPEAKER_27 = "speaker27";
    public const string MESSAGE_27 = "message27";
    public const string EXPRESSION_TYPE_27 = "expressionType27";
    public const string SPEAKER_28 = "speaker28";
    public const string MESSAGE_28 = "message28";
    public const string EXPRESSION_TYPE_28 = "expressionType28";
    public const string SPEAKER_29 = "speaker29";
    public const string MESSAGE_29 = "message29";
    public const string EXPRESSION_TYPE_29 = "expressionType29";
    public const string SPEAKER_30 = "speaker30";
    public const string MESSAGE_30 = "message30";
    public const string EXPRESSION_TYPE_30 = "expressionType30";
    public const string EXPRESSION_TYPE_WHILE_LEAVING = "expressionTypeWhileLeaving";

    public const string USER_ANSWER_01 = "userAnswer01";
    public const string USER_ANSWER_02 = "userAnswer02";
    public const string USER_ANSWER_03 = "userAnswer03";

    [SerializeField] private PipelineJob job01;
    [SerializeField] private PipelineJob job02;
    [SerializeField] private PipelineJob job03;
    [SerializeField] private PipelineJob job04;
    [SerializeField] private PipelineJob job05;
    [SerializeField] private PipelineJob job06;
    [SerializeField] private PipelineJob job07;
    [SerializeField] private PipelineJob job08;
    [SerializeField] private PipelineJob job09;
    [SerializeField] private PipelineJob job10;
    [SerializeField] private PipelineJob job11;
    [SerializeField] private PipelineJob job12;
    [SerializeField] private PipelineJob job13;
    [SerializeField] private PipelineJob job14;
    [SerializeField] private PipelineJob job15;
    [SerializeField] private PipelineJob job16;
    [SerializeField] private PipelineJob job17;
    [SerializeField] private PipelineJob job18;
    [SerializeField] private PipelineJob job19;
    [SerializeField] private PipelineJob job20;
    [SerializeField] private PipelineJob job21;
    [SerializeField] private PipelineJob job22;
    [SerializeField] private PipelineJob job23;
    [SerializeField] private PipelineJob job24;
    [SerializeField] private PipelineJob job25;
    [SerializeField] private PipelineJob job26;
    [SerializeField] private PipelineJob job27;
    [SerializeField] private PipelineJob job28;
    [SerializeField] private PipelineJob job29;
    [SerializeField] private PipelineJob job30;
    [SerializeField] private PipelineJob job31;
    [SerializeField] private PipelineJob job32;
    [SerializeField] private PipelineJob job33;
    [SerializeField] private PipelineJob job34;
    [SerializeField] private PipelineJob job35;
    [SerializeField] private PipelineJob job36;
    [SerializeField] private PipelineJob job37;
    [SerializeField] private PipelineJob job38;
    [SerializeField] private PipelineJob job39;
    [SerializeField] private PipelineJob job40;
    [SerializeField] private PipelineJob job41;
    [SerializeField] private PipelineJob job42;
    [SerializeField] private PipelineJob job43;
    [SerializeField] private PipelineJob job44;
    [SerializeField] private PipelineJob job45;
    [SerializeField] private PipelineJob job46;
    [SerializeField] private PipelineJob job47;
    [SerializeField] private PipelineJob job48;
    [SerializeField] private PipelineJob job49;
    [SerializeField] private PipelineJob job50;
    [SerializeField] private PipelineJob job51;
    [SerializeField] private PipelineJob job52;
    [SerializeField] private PipelineJob job53;
    [SerializeField] private PipelineJob job54;
    [SerializeField] private PipelineJob job55;
    [SerializeField] private PipelineJob job56;
    [SerializeField] private PipelineJob job57;
    [SerializeField] private PipelineJob job58;
    [SerializeField] private PipelineJob job59;
    [SerializeField] private PipelineJob job60;
    [SerializeField] private PipelineJob job61;
    [SerializeField] private PipelineJob job62;
    [SerializeField] private PipelineJob job63;
    [SerializeField] private PipelineJob job64;
    [SerializeField] private PipelineJob job65;
    [SerializeField] private PipelineJob job66;
    [SerializeField] private PipelineJob job67;
    [SerializeField] private PipelineJob job68;
    [SerializeField] private PipelineJob job69;
    [SerializeField] private PipelineJob job70;
    [SerializeField] private PipelineJob job71;
    [SerializeField] private PipelineJob job72;
    [SerializeField] private PipelineJob job73;
    [SerializeField] private PipelineJob job74;
    [SerializeField] private PipelineJob job75;
    [SerializeField] private PipelineJob job76;
    [SerializeField] private PipelineJob job77;
    [SerializeField] private PipelineJob job78;
    [SerializeField] private PipelineJob job79;
    [SerializeField] private PipelineJob job80;
    [SerializeField] private PipelineJob job81;
    [SerializeField] private PipelineJob job82;
    [SerializeField] private PipelineJob job83;
    [SerializeField] private PipelineJob job84;
    [SerializeField] private PipelineJob job85;
    [SerializeField] private PipelineJob job86;
    [SerializeField] private PipelineJob job87;
    [SerializeField] private PipelineJob job88;
    [SerializeField] private PipelineJob job89;
    [SerializeField] private PipelineJob job90;
    [SerializeField] private PipelineJob job91;
    [SerializeField] private PipelineJob job92;
    [SerializeField] private PipelineJob job93;
    [SerializeField] private PipelineJob job94;
    [SerializeField] private PipelineJob job95;
    [SerializeField] private PipelineJob job96;
    [SerializeField] private PipelineJob job97;
    [SerializeField] private PipelineJob job98;
    [SerializeField] private PipelineJob job99;

    public override void InitializePipelineJobs()
    {
    }

    public void GenerateNovel(string userAnswer01, string userAnswer02, string userAnswer03)
    {
        memory[USER_ANSWER_01] = userAnswer01;
        memory[USER_ANSWER_02] = userAnswer02;
        memory[USER_ANSWER_03] = userAnswer03;

        jobs.Enqueue(job01);
        jobs.Enqueue(job02);
        jobs.Enqueue(job03);
        jobs.Enqueue(job04);
        jobs.Enqueue(job05);
        jobs.Enqueue(job06);
        jobs.Enqueue(job07);
        jobs.Enqueue(job08);
        jobs.Enqueue(job09);
        jobs.Enqueue(job10);
        jobs.Enqueue(job11);
        jobs.Enqueue(job12);
        jobs.Enqueue(job13);
        jobs.Enqueue(job14);
        jobs.Enqueue(job15);
        jobs.Enqueue(job16);
        jobs.Enqueue(job17);
        jobs.Enqueue(job18);
        jobs.Enqueue(job19);
        jobs.Enqueue(job20);
        jobs.Enqueue(job21);
        jobs.Enqueue(job22);
        jobs.Enqueue(job23);
        jobs.Enqueue(job24);
        jobs.Enqueue(job25);
        jobs.Enqueue(job26);
        jobs.Enqueue(job27);
        jobs.Enqueue(job28);
        jobs.Enqueue(job29);
        jobs.Enqueue(job30);
        jobs.Enqueue(job31);
        jobs.Enqueue(job32);
        jobs.Enqueue(job33);
        jobs.Enqueue(job34);
        jobs.Enqueue(job35);
        jobs.Enqueue(job36);
        jobs.Enqueue(job37);
        jobs.Enqueue(job38);
        jobs.Enqueue(job39);
        jobs.Enqueue(job40);
        jobs.Enqueue(job41);
        jobs.Enqueue(job42);
        jobs.Enqueue(job43);
        jobs.Enqueue(job44);
        jobs.Enqueue(job45);
        jobs.Enqueue(job46);
        jobs.Enqueue(job47);
        jobs.Enqueue(job48);
        jobs.Enqueue(job49);
        jobs.Enqueue(job50);
        jobs.Enqueue(job51);
        jobs.Enqueue(job52);
        jobs.Enqueue(job53);
        jobs.Enqueue(job54);
        jobs.Enqueue(job55);
        jobs.Enqueue(job56);
        jobs.Enqueue(job57);
        jobs.Enqueue(job58);
        jobs.Enqueue(job59);
        jobs.Enqueue(job60);
        jobs.Enqueue(job61);
        jobs.Enqueue(job62);
        jobs.Enqueue(job63);
        jobs.Enqueue(job64);
        jobs.Enqueue(job65);
        jobs.Enqueue(job66);
        jobs.Enqueue(job67);
        jobs.Enqueue(job68);
        jobs.Enqueue(job69);
        jobs.Enqueue(job70);
        jobs.Enqueue(job71);
        jobs.Enqueue(job72);
        jobs.Enqueue(job73);
        jobs.Enqueue(job74);
        jobs.Enqueue(job75);
        jobs.Enqueue(job76);
        jobs.Enqueue(job77);
        jobs.Enqueue(job78);
        jobs.Enqueue(job79);
        jobs.Enqueue(job80);
        jobs.Enqueue(job81);
        jobs.Enqueue(job82);
        jobs.Enqueue(job83);
        jobs.Enqueue(job84);
        jobs.Enqueue(job85);
        jobs.Enqueue(job86);
        jobs.Enqueue(job87);
        jobs.Enqueue(job88);
        jobs.Enqueue(job89);
        jobs.Enqueue(job90);
        jobs.Enqueue(job91);
        jobs.Enqueue(job92);
        jobs.Enqueue(job93);
        jobs.Enqueue(job94);
        jobs.Enqueue(job95);
        jobs.Enqueue(job96);
        jobs.Enqueue(job97);
        jobs.Enqueue(job98);
        jobs.Enqueue(job99);

        numberOfJobs = jobs.Count;
        numberOfCompletedJobs = 0;

        Debug.Log("Generierung der Novel wird begonnen. Jobs in Warteschlange: " + jobs.Count);
        StartPipeline();
    }

    public override void OnFailure()
    {
        Debug.Log("Generierung der Novel Fehlgeschlagen.");
    }

    public override void OnProgress()
    {
        numberOfCompletedJobs++;

        double percentage = (double)numberOfCompletedJobs / numberOfJobs * 100;
        Debug.Log("Fortschritt: " + numberOfCompletedJobs + " von " + numberOfJobs + " Completed");
    }

    public override void OnSuccess()
    {
        NovelFactory.NovelInformationWrapper wrapper = CreateNovelInformationWrapper();
        VisualNovel novel = NovelFactory.GenerateNovel(wrapper);

        GeneratedNovelManager.Instance().AddUserNovel(novel);
        
        Debug.Log("Novel wurde erfolgreich generiert und gespeichert!");
    }

    public NovelFactory.NovelInformationWrapper CreateNovelInformationWrapper()
    {
        try
        {
            NovelFactory.NovelInformationWrapper wrapper = new NovelFactory.NovelInformationWrapper();
            wrapper.title = this.memory[TITLE];
            wrapper.description = this.memory[DESCRIPTION];
            wrapper.image = Int32.Parse(this.memory[IMAGE]);
            wrapper.nameOfMainCharacter = this.memory[NAME_OF_MAIN_CHARACTER];
            wrapper.nameOfTalkingPartner = this.memory[NAME_OF_TALKING_PARTNER];
            wrapper.context = this.memory[CONTEXT];
            wrapper.backgroundSprite = 0; // Int32.Parse(this.memory[BACKGROUND_SPRITE]);
            wrapper.expressionTypeWhileJoining = Int32.Parse(this.memory[EXPRESSION_TYPE_WHILE_JOINING]);
            wrapper.speaker01 = this.memory[SPEAKER_01];
            wrapper.message01 = this.memory[MESSAGE_01];
            wrapper.expressionType01 = Int32.Parse(this.memory[EXPRESSION_TYPE_01]);
            wrapper.speaker02 = this.memory[SPEAKER_02];
            wrapper.message02 = this.memory[MESSAGE_02];
            wrapper.expressionType02 = Int32.Parse(this.memory[EXPRESSION_TYPE_02]);
            wrapper.speaker03 = this.memory[SPEAKER_03];
            wrapper.message03 = this.memory[MESSAGE_03];
            wrapper.expressionType03 = Int32.Parse(this.memory[EXPRESSION_TYPE_03]);
            wrapper.message04_Option01 = this.memory[MESSAGE_04_OPTION_01];
            wrapper.message04_Option02 = this.memory[MESSAGE_04_OPTION_02];
            wrapper.message04_Option03 = this.memory[MESSAGE_04_OPTION_03];
            wrapper.message04_Option04 = this.memory[MESSAGE_04_OPTION_04];
            wrapper.speaker05 = this.memory[SPEAKER_05];
            wrapper.message05 = this.memory[MESSAGE_05];
            wrapper.expressionType05 = Int32.Parse(this.memory[EXPRESSION_TYPE_05]);
            wrapper.message06_Option01 = this.memory[MESSAGE_06_OPTION_01];
            wrapper.message06_Option02 = this.memory[MESSAGE_06_OPTION_02];
            wrapper.message06_Option03 = this.memory[MESSAGE_06_OPTION_03];
            wrapper.message06_Option04 = this.memory[MESSAGE_06_OPTION_04];
            wrapper.speaker07 = this.memory[SPEAKER_07];
            wrapper.message07 = this.memory[MESSAGE_07];
            wrapper.expressionType07 = Int32.Parse(this.memory[EXPRESSION_TYPE_07]);
            wrapper.speaker08 = this.memory[SPEAKER_08];
            wrapper.message08 = this.memory[MESSAGE_08];
            wrapper.expressionType08 = Int32.Parse(this.memory[EXPRESSION_TYPE_08]);
            wrapper.speaker09 = this.memory[SPEAKER_09];
            wrapper.message09 = this.memory[MESSAGE_09];
            wrapper.expressionType09 = Int32.Parse(this.memory[EXPRESSION_TYPE_09]);
            wrapper.message10_Option01 = this.memory[MESSAGE_10_OPTION_01];
            wrapper.message10_Option02 = this.memory[MESSAGE_10_OPTION_02];
            wrapper.message10_Option03 = this.memory[MESSAGE_10_OPTION_03];
            wrapper.message10_Option04 = this.memory[MESSAGE_10_OPTION_04];
            wrapper.speaker11 = this.memory[SPEAKER_11];
            wrapper.message11 = this.memory[MESSAGE_11];
            wrapper.expressionType11 = Int32.Parse(this.memory[EXPRESSION_TYPE_11]);
            wrapper.speaker12 = this.memory[SPEAKER_12];
            wrapper.message12 = this.memory[MESSAGE_12];
            wrapper.expressionType12 = Int32.Parse(this.memory[EXPRESSION_TYPE_12]);
            wrapper.speaker13 = this.memory[SPEAKER_13];
            wrapper.message13 = this.memory[MESSAGE_13];
            wrapper.expressionType13 = Int32.Parse(this.memory[EXPRESSION_TYPE_13]);
            wrapper.speaker14 = this.memory[SPEAKER_14];
            wrapper.message14 = this.memory[MESSAGE_14];
            wrapper.expressionType14 = Int32.Parse(this.memory[EXPRESSION_TYPE_14]);
            wrapper.speaker15 = this.memory[SPEAKER_15];
            wrapper.message15 = this.memory[MESSAGE_15];
            wrapper.expressionType15 = Int32.Parse(this.memory[EXPRESSION_TYPE_15]);
            wrapper.speaker16 = this.memory[SPEAKER_16];
            wrapper.message16 = this.memory[MESSAGE_16];
            wrapper.expressionType16 = Int32.Parse(this.memory[EXPRESSION_TYPE_16]);
            wrapper.speaker17 = this.memory[SPEAKER_17];
            wrapper.message17 = this.memory[MESSAGE_17];
            wrapper.expressionType17 = Int32.Parse(this.memory[EXPRESSION_TYPE_17]);
            wrapper.speaker18 = this.memory[SPEAKER_18];
            wrapper.message18 = this.memory[MESSAGE_18];
            wrapper.expressionType18 = Int32.Parse(this.memory[EXPRESSION_TYPE_18]);
            wrapper.speaker19 = this.memory[SPEAKER_19];
            wrapper.message19 = this.memory[MESSAGE_19];
            wrapper.expressionType19 = Int32.Parse(this.memory[EXPRESSION_TYPE_19]);
            wrapper.speaker20 = this.memory[SPEAKER_20];
            wrapper.message20 = this.memory[MESSAGE_20];
            wrapper.expressionType20 = Int32.Parse(this.memory[EXPRESSION_TYPE_20]);
            wrapper.message21_Option01 = this.memory[MESSAGE_21_OPTION_01];
            wrapper.message21_Option02 = this.memory[MESSAGE_21_OPTION_02];
            wrapper.message21_Option03 = this.memory[MESSAGE_21_OPTION_03];
            wrapper.message21_Option04 = this.memory[MESSAGE_21_OPTION_04];
            wrapper.speaker22 = this.memory[SPEAKER_22];
            wrapper.message22 = this.memory[MESSAGE_22];
            wrapper.expressionType22 = Int32.Parse(this.memory[EXPRESSION_TYPE_22]);
            wrapper.speaker23 = this.memory[SPEAKER_23];
            wrapper.message23 = this.memory[MESSAGE_23];
            wrapper.expressionType23 = Int32.Parse(this.memory[EXPRESSION_TYPE_23]);
            wrapper.speaker24 = this.memory[SPEAKER_24];
            wrapper.message24 = this.memory[MESSAGE_24];
            wrapper.expressionType24 = Int32.Parse(this.memory[EXPRESSION_TYPE_24]);
            wrapper.message25_Option01 = this.memory[MESSAGE_25_OPTION_01];
            wrapper.message25_Option02 = this.memory[MESSAGE_25_OPTION_02];
            wrapper.message25_Option03 = this.memory[MESSAGE_25_OPTION_03];
            wrapper.message25_Option04 = this.memory[MESSAGE_25_OPTION_04];
            wrapper.speaker26 = this.memory[SPEAKER_26];
            wrapper.message26 = this.memory[MESSAGE_26];
            wrapper.expressionType26 = Int32.Parse(this.memory[EXPRESSION_TYPE_26]);
            wrapper.speaker27 = this.memory[SPEAKER_27];
            wrapper.message27 = this.memory[MESSAGE_27];
            wrapper.expressionType27 = Int32.Parse(this.memory[EXPRESSION_TYPE_27]);
            wrapper.speaker28 = this.memory[SPEAKER_28];
            wrapper.message28 = this.memory[MESSAGE_28];
            wrapper.expressionType28 = Int32.Parse(this.memory[EXPRESSION_TYPE_28]);
            wrapper.speaker29 = this.memory[SPEAKER_29];
            wrapper.message29 = this.memory[MESSAGE_29];
            wrapper.expressionType29 = Int32.Parse(this.memory[EXPRESSION_TYPE_29]);
            wrapper.speaker30 = this.memory[SPEAKER_30];
            wrapper.message30 = this.memory[MESSAGE_30];
            wrapper.expressionType30 = Int32.Parse(this.memory[EXPRESSION_TYPE_30]);
            wrapper.expressionTypeWhileLeaving = Int32.Parse(this.memory[EXPRESSION_TYPE_WHILE_LEAVING]);
            return wrapper;
        } catch
        {
            Debug.Log("Failed to transfer data to new novel.");
            return new NovelFactory.NovelInformationWrapper();
        }
    }
}
