namespace Assets._Scripts.Player.Kite_Novels.Visual_Novel_Formatter
{
    public enum NovelKeyWord
    {
        NONE,

        SZENE_BUERO,

        EINTRITT_CHARAKTER_01,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ERSCHROCKEN,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_GENERVT,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ABLEHNEND,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ERSTAUNT,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_FRAGEND,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_KRITISCH,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LACHEND,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAECHELN,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_NEUTRAL,
        EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_STOLZ,

        CHARAKTER_01_SCHAUT,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_GENERVT,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_FRAGEND,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_KRITISCH,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LACHEND,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LAECHELN,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL,
        CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_STOLZ,

        CHARAKTER_01_SPRICHT,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_GENERVT,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_FRAGEND,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_KRITISCH,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LACHEND,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LAECHELN,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL,
        CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_STOLZ,

        EINTRITT_CHARAKTER_02,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ERSCHROCKEN,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_GENERVT,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ABLEHNEND,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ERSTAUNT,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_FRAGEND,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_KRITISCH,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LACHEND,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAECHELN,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_NEUTRAL,
        EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_STOLZ,

        CHARAKTER_02_SCHAUT,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_GENERVT,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_FRAGEND,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_KRITISCH,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LACHEND,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LAECHELN,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL,
        CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_STOLZ,

        CHARAKTER_02_SPRICHT,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_GENERVT,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_FRAGEND,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_KRITISCH,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LACHEND,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LAECHELN,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL,
        CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_STOLZ,

        EINTRITT_CHARAKTER_03,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ERSCHROCKEN,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_GENERVT,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ABLEHNEND,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ERSTAUNT,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_FRAGEND,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_KRITISCH,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LACHEND,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAECHELN,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_NEUTRAL,
        EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_STOLZ,

        CHARAKTER_03_SCHAUT,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_GENERVT,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_FRAGEND,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_KRITISCH,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LACHEND,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LAECHELN,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL,
        CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_STOLZ,

        CHARAKTER_03_SPRICHT,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_GENERVT,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_FRAGEND,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_KRITISCH,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LACHEND,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LAECHELN,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL,
        CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_STOLZ,

        SPIELER_CHARAKTER_SPRICHT,

        INFO_NACHRICHT_WIRD_ANGEZEIGT,

        SOUND_ABSPIELEN_WATER_POURING,
        SOUND_ABSPIELEN_LEAVE_SCENE,
        SOUND_ABSPIELEN_TELEPHONE_CALL,
        SOUND_ABSPIELEN_PAPER_SOUND,
        SOUND_ABSPIELEN_MAN_LAUGHING,

        ANIMATION_ABSPIELEN_WATER_POURING,

        DIALOG_OPTIONEN,

        ENDE,

        FREITEXT_EINGABE,

        GPT_PROMPT_MIT_DEFAULT_COMPLETION_HANDLER,

        PERSISTENTES_SPEICHERN,

        VARIABLE_SETZEN,
        VARIABLE_AUS_BOOLSCHEM_AUSDRUCK_BESTIMMEN,

        FEEDBACK_HINZUFUEGEN,
        FEEDBACK_UNTER_BEDINGUNG_HINZUFUEGEN,

        RELEVANTER_BIAS_FINANZIERUNGSZUGANG,
        RELEVANTER_BIAS_GENDER_PAY_GAP,
        RELEVANTER_BIAS_UNTERBEWERTUNG_WEIBLICH_GEFUEHRTER_UNTERNEHMEN,
        RELEVANTER_BIAS_RISK_AVERSION_BIAS,
        RELEVANTER_BIAS_BESTAETIGUNGSVERZERRUNG,
        RELEVANTER_BIAS_TOKENISM,
        RELEVANTER_BIAS_BIAS_IN_DER_WAHRNEHMUNG_VON_FUEHRUNGSFAEHIGKEITEN,
        RELEVANTER_BIAS_RASSISTISCHE_UND_ETHNISCHE_BIASES,
        RELEVANTER_BIAS_SOZIOOEKONOMISCHE_BIASES,
        RELEVANTER_BIAS_ALTER_UND_GENERATIONEN_BIASES,
        RELEVANTER_BIAS_SEXUALITAETSBEZOGENE_BIASES,
        RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_BEHINDERUNGEN,
        RELEVANTER_BIAS_STEREOTYPE_GEGENUEBER_FRAUEN_IN_NICHT_TRADITIONELLEN_BRANCHEN,
        RELEVANTER_BIAS_KULTURELLE_UND_RELIGIOESE_BIASES,
        RELEVANTER_BIAS_MATERNAL_BIAS,
        RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_KINDERN,
        RELEVANTER_BIAS_ERWARTUNGSHALTUNG_BEZUEGLICH_FAMILIENPLANUNG,
        RELEVANTER_BIAS_WORK_LIFE_BALANCE_ERWARTUNGEN,
        RELEVANTER_BIAS_GESCHLECHTSSPEZIFISCHE_STEREOTYPEN,
        RELEVANTER_BIAS_TIGHTROPE_BIAS,
        RELEVANTER_BIAS_MIKROAGGRESSIONEN,
        RELEVANTER_BIAS_LEISTUNGSATTRIBUTIONS_BIAS,
        RELEVANTER_BIAS_BIAS_IN_MEDIEN_UND_WERBUNG,
        RELEVANTER_BIAS_UNBEWUSSTE_BIAS_IN_DER_KOMMUNIKATION,
        RELEVANTER_BIAS_PROVE_IT_AGAIN_BIAS,
        RELEVANTER_BIAS_HETERONORMATIVITAET_BIAS,
        RELEVANTER_BIAS_BENEVOLENTER_SEXISMUS_BIAS
    }

    public class NovelKeyWordHelper
    {
        public static NovelKeyWord GetKeyWordOutOfValue(string value)
        {
            switch (value)
            {
                case (NovelKeyWordValue.SZENE_BUERO): return NovelKeyWord.SZENE_BUERO;

                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.CHARAKTER_01_SCHAUT_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.CHARAKTER_01_SPRICHT_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.CHARAKTER_02_SCHAUT_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.CHARAKTER_02_SPRICHT_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.CHARAKTER_03_SCHAUT_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ERSCHROCKEN;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_GENERVT):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_GENERVT;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_UNZUFRIEDEN;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ABLEHNEND;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_ERSTAUNT;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_FRAGEND):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_FRAGEND;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_KRITISCH):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_KRITISCH;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LAECHELN_GROSS;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LACHEND):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LACHEND;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LAECHELN):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_LAECHELN;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL_ENTSPANNT;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_NEUTRAL;
                case (NovelKeyWordValue.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_STOLZ):
                    return NovelKeyWord.CHARAKTER_03_SPRICHT_GESICHTSAUSDRUCK_STOLZ;

                case (NovelKeyWordValue.SPIELER_CHARAKTER_SPRICHT): return NovelKeyWord.SPIELER_CHARAKTER_SPRICHT;
                case (NovelKeyWordValue.INFO_NACHRICHT_WIRD_ANGEZEIGT):
                    return NovelKeyWord.INFO_NACHRICHT_WIRD_ANGEZEIGT;
                case (NovelKeyWordValue.SOUND_ABSPIELEN_WATER_POURING):
                    return NovelKeyWord.SOUND_ABSPIELEN_WATER_POURING;
                case (NovelKeyWordValue.SOUND_ABSPIELEN_LEAVE_SCENE): return NovelKeyWord.SOUND_ABSPIELEN_LEAVE_SCENE;
                case (NovelKeyWordValue.SOUND_ABSPIELEN_TELEPHONE_CALL):
                    return NovelKeyWord.SOUND_ABSPIELEN_TELEPHONE_CALL;
                case (NovelKeyWordValue.SOUND_ABSPIELEN_PAPER_SOUND): return NovelKeyWord.SOUND_ABSPIELEN_PAPER_SOUND;
                case (NovelKeyWordValue.SOUND_ABSPIELEN_MAN_LAUGHING): return NovelKeyWord.SOUND_ABSPIELEN_MAN_LAUGHING;
                case (NovelKeyWordValue.ANIMATION_ABSPIELEN_WATER_POURING):
                    return NovelKeyWord.ANIMATION_ABSPIELEN_WATER_POURING;
                case (NovelKeyWordValue.DIALOG_OPTIONEN): return NovelKeyWord.DIALOG_OPTIONEN;
                case (NovelKeyWordValue.ENDE): return NovelKeyWord.ENDE;
                case (NovelKeyWordValue.FREITEXT_EINGABE): return NovelKeyWord.FREITEXT_EINGABE;
                case (NovelKeyWordValue.GPT_PROMPT_MIT_DEFAULT_COMPLETION_HANDLER):
                    return NovelKeyWord.GPT_PROMPT_MIT_DEFAULT_COMPLETION_HANDLER;
                case (NovelKeyWordValue.PERSISTENTES_SPEICHERN): return NovelKeyWord.PERSISTENTES_SPEICHERN;
                case (NovelKeyWordValue.VARIABLE_SETZEN): return NovelKeyWord.VARIABLE_SETZEN;
                case (NovelKeyWordValue.VARIABLE_AUS_BOOLSCHEM_AUSDRUCK_BESTIMMEN):
                    return NovelKeyWord.VARIABLE_AUS_BOOLSCHEM_AUSDRUCK_BESTIMMEN;
                case (NovelKeyWordValue.FEEDBACK_HINZUFUEGEN): return NovelKeyWord.FEEDBACK_HINZUFUEGEN;
                case (NovelKeyWordValue.FEEDBACK_UNTER_BEDINGUNG_HINZUFUEGEN):
                    return NovelKeyWord.FEEDBACK_UNTER_BEDINGUNG_HINZUFUEGEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_FINANZIERUNGSZUGANG):
                    return NovelKeyWord.RELEVANTER_BIAS_FINANZIERUNGSZUGANG;
                case (NovelKeyWordValue.RELEVANTER_BIAS_GENDER_PAY_GAP):
                    return NovelKeyWord.RELEVANTER_BIAS_GENDER_PAY_GAP;
                case (NovelKeyWordValue.RELEVANTER_BIAS_UNTERBEWERTUNG_WEIBLICH_GEFUEHRTER_UNTERNEHMEN):
                    return NovelKeyWord.RELEVANTER_BIAS_UNTERBEWERTUNG_WEIBLICH_GEFUEHRTER_UNTERNEHMEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_RISK_AVERSION_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_RISK_AVERSION_BIAS;
                case (NovelKeyWordValue.RELEVANTER_BIAS_BESTAETIGUNGSVERZERRUNG):
                    return NovelKeyWord.RELEVANTER_BIAS_BESTAETIGUNGSVERZERRUNG;
                case (NovelKeyWordValue.RELEVANTER_BIAS_TOKENISM): return NovelKeyWord.RELEVANTER_BIAS_TOKENISM;
                case (NovelKeyWordValue.RELEVANTER_BIAS_BIAS_IN_DER_WAHRNEHMUNG_VON_FUEHRUNGSFAEHIGKEITEN):
                    return NovelKeyWord.RELEVANTER_BIAS_BIAS_IN_DER_WAHRNEHMUNG_VON_FUEHRUNGSFAEHIGKEITEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_RASSISTISCHE_UND_ETHNISCHE_BIASES):
                    return NovelKeyWord.RELEVANTER_BIAS_RASSISTISCHE_UND_ETHNISCHE_BIASES;
                case (NovelKeyWordValue.RELEVANTER_BIAS_SOZIOOEKONOMISCHE_BIASES):
                    return NovelKeyWord.RELEVANTER_BIAS_SOZIOOEKONOMISCHE_BIASES;
                case (NovelKeyWordValue.RELEVANTER_BIAS_ALTER_UND_GENERATIONEN_BIASES):
                    return NovelKeyWord.RELEVANTER_BIAS_ALTER_UND_GENERATIONEN_BIASES;
                case (NovelKeyWordValue.RELEVANTER_BIAS_SEXUALITAETSBEZOGENE_BIASES):
                    return NovelKeyWord.RELEVANTER_BIAS_SEXUALITAETSBEZOGENE_BIASES;
                case (NovelKeyWordValue.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_BEHINDERUNGEN):
                    return NovelKeyWord.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_BEHINDERUNGEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_STEREOTYPE_GEGENUEBER_FRAUEN_IN_NICHT_TRADITIONELLEN_BRANCHEN):
                    return NovelKeyWord.RELEVANTER_BIAS_STEREOTYPE_GEGENUEBER_FRAUEN_IN_NICHT_TRADITIONELLEN_BRANCHEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_KULTURELLE_UND_RELIGIOESE_BIASES):
                    return NovelKeyWord.RELEVANTER_BIAS_KULTURELLE_UND_RELIGIOESE_BIASES;
                case (NovelKeyWordValue.RELEVANTER_BIAS_MATERNAL_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_MATERNAL_BIAS;
                case (NovelKeyWordValue.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_KINDERN):
                    return NovelKeyWord.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_KINDERN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_ERWARTUNGSHALTUNG_BEZUEGLICH_FAMILIENPLANUNG):
                    return NovelKeyWord.RELEVANTER_BIAS_ERWARTUNGSHALTUNG_BEZUEGLICH_FAMILIENPLANUNG;
                case (NovelKeyWordValue.RELEVANTER_BIAS_WORK_LIFE_BALANCE_ERWARTUNGEN):
                    return NovelKeyWord.RELEVANTER_BIAS_WORK_LIFE_BALANCE_ERWARTUNGEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_GESCHLECHTSSPEZIFISCHE_STEREOTYPEN):
                    return NovelKeyWord.RELEVANTER_BIAS_GESCHLECHTSSPEZIFISCHE_STEREOTYPEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_TIGHTROPE_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_TIGHTROPE_BIAS;
                case (NovelKeyWordValue.RELEVANTER_BIAS_MIKROAGGRESSIONEN):
                    return NovelKeyWord.RELEVANTER_BIAS_MIKROAGGRESSIONEN;
                case (NovelKeyWordValue.RELEVANTER_BIAS_LEISTUNGSATTRIBUTIONS_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_LEISTUNGSATTRIBUTIONS_BIAS;
                case (NovelKeyWordValue.RELEVANTER_BIAS_BIAS_IN_MEDIEN_UND_WERBUNG):
                    return NovelKeyWord.RELEVANTER_BIAS_BIAS_IN_MEDIEN_UND_WERBUNG;
                case (NovelKeyWordValue.RELEVANTER_BIAS_UNBEWUSSTE_BIAS_IN_DER_KOMMUNIKATION):
                    return NovelKeyWord.RELEVANTER_BIAS_UNBEWUSSTE_BIAS_IN_DER_KOMMUNIKATION;
                case (NovelKeyWordValue.RELEVANTER_BIAS_PROVE_IT_AGAIN_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_PROVE_IT_AGAIN_BIAS;
                case (NovelKeyWordValue.RELEVANTER_BIAS_HETERONORMATIVITAET_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_HETERONORMATIVITAET_BIAS;
                case (NovelKeyWordValue.RELEVANTER_BIAS_BENEVOLENTER_SEXISMUS_BIAS):
                    return NovelKeyWord.RELEVANTER_BIAS_BENEVOLENTER_SEXISMUS_BIAS;
                default: return NovelKeyWord.NONE;
            }
        }
    }
}