public enum NovelKeyWord
{
    NONE,

    SZENE_BUERO,

    EINTRITT_CHARAKTER_01,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_RELAXED,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ASTONISHED,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_REFUSING,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_SMILING,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_FRIENDLY,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAUGHING,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_CRITICAL,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_DECISION_NO,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_HAPPY,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_PROUD,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_SCARED,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_QUESTIONING,
    EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_DEFEATED,

    CHARAKTER_SPRICHT_CHARAKTER_01,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_RELAXED,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_ASTONISHED,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_REFUSING,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_SMILING,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_FRIENDLY,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_LAUGHING,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_CRITICAL,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_DECISION_NO,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_HAPPY,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_PROUD,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_SCARED,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_QUESTIONING,
    CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_DEFEATED,

    EINTRITT_CHARAKTER_02,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_RELAXED,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ASTONISHED,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_REFUSING,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_SMILING,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_FRIENDLY,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAUGHING,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_CRITICAL,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_DECISION_NO,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_HAPPY,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_PROUD,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_SCARED,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_QUESTIONING,
    EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_DEFEATED,

    CHARAKTER_SPRICHT_CHARAKTER_02,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_RELAXED,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_ASTONISHED,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_REFUSING,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_SMILING,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_FRIENDLY,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_LAUGHING,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_CRITICAL,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_DECISION_NO,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_HAPPY,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_PROUD,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_SCARED,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_QUESTIONING,
    CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_DEFEATED,

    EINTRITT_CHARAKTER_03,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_RELAXED,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ASTONISHED,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_REFUSING,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_SMILING,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_FRIENDLY,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAUGHING,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_CRITICAL,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_DECISION_NO,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_HAPPY,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_PROUD,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_SCARED,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_QUESTIONING,
    EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_DEFEATED,

    CHARAKTER_SPRICHT_CHARAKTER_03,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_RELAXED,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_ASTONISHED,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_REFUSING,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_SMILING,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_FRIENDLY,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_LAUGHING,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_CRITICAL,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_DECISION_NO,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_HAPPY,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_PROUD,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_SCARED,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_QUESTIONING,
    CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_DEFEATED,

    SPIELER_CHARAKTER_SPRICHT,

    INFO_NACHRICHT_WIRD_ANGEZEIGT,

    SOUND_ABSPIELEN_WATER_POURING,
    SOUND_ABSPIELEN_LEAVE_SCENE,
    SOUND_ABSPIELEN_TELEPHONE_CALL,
    SOUND_ABSPIELEN_PAPER_SOUND,
    SOUND_ABSPIELEN_MAN_LAUGHING,

    ANIMATION_ABSPIELEN_WATER_POURING,

    DIALOG_OPTIONEN,

    ENDE,

    FREITEXT_EINGABE,

    GPT_PROMPT_MIT_DEFAULT_COMPLETION_HANDLER,

    PERSISTENTES_SPEICHERN,

    RELEVANTER_BIAS_FINANZIERUNGSZUGANG,
    RELEVANTER_BIAS_GENDER_PAY_GAP,
    RELEVANTER_BIAS_UNTERBEWERTUNG_WEIBLICH_GEFUEHRTER_UNTERNEHMEN,
    RELEVANTER_BIAS_RISK_AVERSION_BIAS,
    RELEVANTER_BIAS_BESTAETIGUNGSVERZERRUNG,
    RELEVANTER_BIAS_TOKENISM,
    RELEVANTER_BIAS_BIAS_IN_DER_WAHRNEHMUNG_VON_FUEHRUNGSFAEHIGKEITEN,
    RELEVANTER_BIAS_RASSISTISCHE_UND_ETHNISCHE_BIASES,
    RELEVANTER_BIAS_SOZIOOEKONOMISCHE_BIASES,
    RELEVANTER_BIAS_ALTER_UND_GENERATIONEN_BIASES,
    RELEVANTER_BIAS_SEXUALITAETSBEZOGENE_BIASES,
    RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_BEHINDERUNGEN,
    RELEVANTER_BIAS_STEREOTYPE_GEGENUEBER_FRAUEN_IN_NICHT_TRADITIONELLEN_BRANCHEN,
    RELEVANTER_BIAS_KULTURELLE_UND_RELIGIOESE_BIASES,
    RELEVANTER_BIAS_MATERNAL_BIAS,
    RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_KINDERN,
    RELEVANTER_BIAS_ERWARTUNGSHALTUNG_BEZUEGLICH_FAMILIENPLANUNG,
    RELEVANTER_BIAS_WORK_LIFE_BALANCE_ERWARTUNGEN,
    RELEVANTER_BIAS_GESCHLECHTSSPEZIFISCHE_STEREOTYPEN,
    RELEVANTER_BIAS_TIGHTROPE_BIAS,
    RELEVANTER_BIAS_MIKROAGGRESSIONEN,
    RELEVANTER_BIAS_LEISTUNGSATTRIBUTIONS_BIAS,
    RELEVANTER_BIAS_BIAS_IN_MEDIEN_UND_WERBUNG,
    RELEVANTER_BIAS_UNBEWUSSTE_BIAS_IN_DER_KOMMUNIKATION,
    RELEVANTER_BIAS_PROVE_IT_AGAIN_BIAS
}

public class NovelKeyWordHelper
{
    public static NovelKeyWord GetKeyWordOutOfValue(string value)
    {
        switch (value)
        {
            case (NovelKeyWordValue.SZENE_BUERO): return NovelKeyWord.SZENE_BUERO;

            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01): return NovelKeyWord.EINTRITT_CHARAKTER_01;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_RELAXED): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_RELAXED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ASTONISHED): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_ASTONISHED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_REFUSING): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_REFUSING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_SMILING): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_SMILING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_FRIENDLY): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_FRIENDLY;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAUGHING): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_LAUGHING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_CRITICAL): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_CRITICAL;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_DECISION_NO): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_DECISION_NO;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_HAPPY): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_HAPPY;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_PROUD): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_PROUD;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_SCARED): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_SCARED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_QUESTIONING): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_QUESTIONING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_DEFEATED): return NovelKeyWord.EINTRITT_CHARAKTER_01_GESICHTSAUSDRUCK_DEFEATED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_RELAXED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_RELAXED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_ASTONISHED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_ASTONISHED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_REFUSING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_REFUSING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_SMILING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_SMILING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_FRIENDLY): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_FRIENDLY;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_LAUGHING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_LAUGHING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_CRITICAL): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_CRITICAL;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_DECISION_NO): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_DECISION_NO;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_HAPPY): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_HAPPY;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_PROUD): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_PROUD;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_SCARED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_SCARED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_QUESTIONING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_QUESTIONING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_DEFEATED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_01_GESICHTSAUSDRUCK_DEFEATED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02): return NovelKeyWord.EINTRITT_CHARAKTER_02;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_RELAXED): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_RELAXED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ASTONISHED): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_ASTONISHED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_REFUSING): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_REFUSING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_SMILING): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_SMILING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_FRIENDLY): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_FRIENDLY;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAUGHING): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_LAUGHING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_CRITICAL): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_CRITICAL;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_DECISION_NO): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_DECISION_NO;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_HAPPY): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_HAPPY;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_PROUD): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_PROUD;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_SCARED): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_SCARED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_QUESTIONING): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_QUESTIONING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_DEFEATED): return NovelKeyWord.EINTRITT_CHARAKTER_02_GESICHTSAUSDRUCK_DEFEATED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_RELAXED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_RELAXED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_ASTONISHED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_ASTONISHED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_REFUSING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_REFUSING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_SMILING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_SMILING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_FRIENDLY): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_FRIENDLY;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_LAUGHING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_LAUGHING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_CRITICAL): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_CRITICAL;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_DECISION_NO): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_DECISION_NO;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_HAPPY): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_HAPPY;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_PROUD): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_PROUD;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_SCARED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_SCARED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_QUESTIONING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_QUESTIONING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_DEFEATED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_02_GESICHTSAUSDRUCK_DEFEATED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03): return NovelKeyWord.EINTRITT_CHARAKTER_03;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_RELAXED): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_RELAXED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ASTONISHED): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_ASTONISHED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_REFUSING): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_REFUSING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_SMILING): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_SMILING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_FRIENDLY): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_FRIENDLY;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAUGHING): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_LAUGHING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_CRITICAL): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_CRITICAL;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_DECISION_NO): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_DECISION_NO;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_HAPPY): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_HAPPY;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_PROUD): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_PROUD;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_SCARED): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_SCARED;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_QUESTIONING): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_QUESTIONING;
            case (NovelKeyWordValue.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_DEFEATED): return NovelKeyWord.EINTRITT_CHARAKTER_03_GESICHTSAUSDRUCK_DEFEATED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_RELAXED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_RELAXED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_ASTONISHED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_ASTONISHED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_REFUSING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_REFUSING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_SMILING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_SMILING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_FRIENDLY): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_FRIENDLY;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_LAUGHING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_LAUGHING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_CRITICAL): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_CRITICAL;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_DECISION_NO): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_DECISION_NO;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_HAPPY): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_HAPPY;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_PROUD): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_PROUD;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_SCARED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_SCARED;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_QUESTIONING): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_QUESTIONING;
            case (NovelKeyWordValue.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_DEFEATED): return NovelKeyWord.CHARAKTER_SPRICHT_CHARAKTER_03_GESICHTSAUSDRUCK_DEFEATED;
            case (NovelKeyWordValue.SPIELER_CHARAKTER_SPRICHT): return NovelKeyWord.SPIELER_CHARAKTER_SPRICHT;
            case (NovelKeyWordValue.INFO_NACHRICHT_WIRD_ANGEZEIGT): return NovelKeyWord.INFO_NACHRICHT_WIRD_ANGEZEIGT;
            case (NovelKeyWordValue.SOUND_ABSPIELEN_WATER_POURING): return NovelKeyWord.SOUND_ABSPIELEN_WATER_POURING;
            case (NovelKeyWordValue.SOUND_ABSPIELEN_LEAVE_SCENE): return NovelKeyWord.SOUND_ABSPIELEN_LEAVE_SCENE;
            case (NovelKeyWordValue.SOUND_ABSPIELEN_TELEPHONE_CALL): return NovelKeyWord.SOUND_ABSPIELEN_TELEPHONE_CALL;
            case (NovelKeyWordValue.SOUND_ABSPIELEN_PAPER_SOUND): return NovelKeyWord.SOUND_ABSPIELEN_PAPER_SOUND;
            case (NovelKeyWordValue.SOUND_ABSPIELEN_MAN_LAUGHING): return NovelKeyWord.SOUND_ABSPIELEN_MAN_LAUGHING;
            case (NovelKeyWordValue.ANIMATION_ABSPIELEN_WATER_POURING): return NovelKeyWord.ANIMATION_ABSPIELEN_WATER_POURING;
            case (NovelKeyWordValue.DIALOG_OPTIONEN): return NovelKeyWord.DIALOG_OPTIONEN;
            case (NovelKeyWordValue.ENDE): return NovelKeyWord.ENDE;
            case (NovelKeyWordValue.FREITEXT_EINGABE): return NovelKeyWord.FREITEXT_EINGABE;
            case (NovelKeyWordValue.GPT_PROMPT_MIT_DEFAULT_COMPLETION_HANDLER): return NovelKeyWord.GPT_PROMPT_MIT_DEFAULT_COMPLETION_HANDLER;
            case (NovelKeyWordValue.PERSISTENTES_SPEICHERN): return NovelKeyWord.PERSISTENTES_SPEICHERN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_FINANZIERUNGSZUGANG): return NovelKeyWord.RELEVANTER_BIAS_FINANZIERUNGSZUGANG;
            case (NovelKeyWordValue.RELEVANTER_BIAS_GENDER_PAY_GAP): return NovelKeyWord.RELEVANTER_BIAS_GENDER_PAY_GAP;
            case (NovelKeyWordValue.RELEVANTER_BIAS_UNTERBEWERTUNG_WEIBLICH_GEFUEHRTER_UNTERNEHMEN): return NovelKeyWord.RELEVANTER_BIAS_UNTERBEWERTUNG_WEIBLICH_GEFUEHRTER_UNTERNEHMEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_RISK_AVERSION_BIAS): return NovelKeyWord.RELEVANTER_BIAS_RISK_AVERSION_BIAS;
            case (NovelKeyWordValue.RELEVANTER_BIAS_BESTAETIGUNGSVERZERRUNG): return NovelKeyWord.RELEVANTER_BIAS_BESTAETIGUNGSVERZERRUNG;
            case (NovelKeyWordValue.RELEVANTER_BIAS_TOKENISM): return NovelKeyWord.RELEVANTER_BIAS_TOKENISM;
            case (NovelKeyWordValue.RELEVANTER_BIAS_BIAS_IN_DER_WAHRNEHMUNG_VON_FUEHRUNGSFAEHIGKEITEN): return NovelKeyWord.RELEVANTER_BIAS_BIAS_IN_DER_WAHRNEHMUNG_VON_FUEHRUNGSFAEHIGKEITEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_RASSISTISCHE_UND_ETHNISCHE_BIASES): return NovelKeyWord.RELEVANTER_BIAS_RASSISTISCHE_UND_ETHNISCHE_BIASES;
            case (NovelKeyWordValue.RELEVANTER_BIAS_SOZIOOEKONOMISCHE_BIASES): return NovelKeyWord.RELEVANTER_BIAS_SOZIOOEKONOMISCHE_BIASES;
            case (NovelKeyWordValue.RELEVANTER_BIAS_ALTER_UND_GENERATIONEN_BIASES): return NovelKeyWord.RELEVANTER_BIAS_ALTER_UND_GENERATIONEN_BIASES;
            case (NovelKeyWordValue.RELEVANTER_BIAS_SEXUALITAETSBEZOGENE_BIASES): return NovelKeyWord.RELEVANTER_BIAS_SEXUALITAETSBEZOGENE_BIASES;
            case (NovelKeyWordValue.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_BEHINDERUNGEN): return NovelKeyWord.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_BEHINDERUNGEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_STEREOTYPE_GEGENUEBER_FRAUEN_IN_NICHT_TRADITIONELLEN_BRANCHEN): return NovelKeyWord.RELEVANTER_BIAS_STEREOTYPE_GEGENUEBER_FRAUEN_IN_NICHT_TRADITIONELLEN_BRANCHEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_KULTURELLE_UND_RELIGIOESE_BIASES): return NovelKeyWord.RELEVANTER_BIAS_KULTURELLE_UND_RELIGIOESE_BIASES;
            case (NovelKeyWordValue.RELEVANTER_BIAS_MATERNAL_BIAS): return NovelKeyWord.RELEVANTER_BIAS_MATERNAL_BIAS;
            case (NovelKeyWordValue.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_KINDERN): return NovelKeyWord.RELEVANTER_BIAS_BIASES_GEGENUEBER_FRAUEN_MIT_KINDERN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_ERWARTUNGSHALTUNG_BEZUEGLICH_FAMILIENPLANUNG): return NovelKeyWord.RELEVANTER_BIAS_ERWARTUNGSHALTUNG_BEZUEGLICH_FAMILIENPLANUNG;
            case (NovelKeyWordValue.RELEVANTER_BIAS_WORK_LIFE_BALANCE_ERWARTUNGEN): return NovelKeyWord.RELEVANTER_BIAS_WORK_LIFE_BALANCE_ERWARTUNGEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_GESCHLECHTSSPEZIFISCHE_STEREOTYPEN): return NovelKeyWord.RELEVANTER_BIAS_GESCHLECHTSSPEZIFISCHE_STEREOTYPEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_TIGHTROPE_BIAS): return NovelKeyWord.RELEVANTER_BIAS_TIGHTROPE_BIAS;
            case (NovelKeyWordValue.RELEVANTER_BIAS_MIKROAGGRESSIONEN): return NovelKeyWord.RELEVANTER_BIAS_MIKROAGGRESSIONEN;
            case (NovelKeyWordValue.RELEVANTER_BIAS_LEISTUNGSATTRIBUTIONS_BIAS): return NovelKeyWord.RELEVANTER_BIAS_LEISTUNGSATTRIBUTIONS_BIAS;
            case (NovelKeyWordValue.RELEVANTER_BIAS_BIAS_IN_MEDIEN_UND_WERBUNG): return NovelKeyWord.RELEVANTER_BIAS_BIAS_IN_MEDIEN_UND_WERBUNG;
            case (NovelKeyWordValue.RELEVANTER_BIAS_UNBEWUSSTE_BIAS_IN_DER_KOMMUNIKATION): return NovelKeyWord.RELEVANTER_BIAS_UNBEWUSSTE_BIAS_IN_DER_KOMMUNIKATION;
            case (NovelKeyWordValue.RELEVANTER_BIAS_PROVE_IT_AGAIN_BIAS): return NovelKeyWord.RELEVANTER_BIAS_PROVE_IT_AGAIN_BIAS;
            default: return NovelKeyWord.NONE;
        }
    }
}